# Spring Config, Gateway Routing, Filter
spring:
  application:
    name: core-gateway
  cloud:
    gateway:
      routes:
      # ----------------------------------
      # Spring Security Oauth
      # ----------------------------------
      - id: core-oauth-security
        uri: lb://core-security
        predicates:
          - Path= /oauth/**
      # --------------------
      # Web Member
      # --------------------
      - id: app-member
        uri: lb://web-member
        predicates:
          - Path= /api/member/pvt/{segment}
        filters:
          - SetPath= /api/microsite/member/{segment}
          - JwtFilter= name,true

      - id: app-member-pub
        uri: lb://web-member
        predicates:
          - Path= /api/member/pub/{segment}
        filters:
          - SetPath= /api/microsite/member/pub/{segment}
          - BasicFilter= name,true
      # --------------------
      # Web Order
      # --------------------
      - id: app-trade
        uri: lb://web-order
        predicates:
          - Path= /api/order/{segment}
        filters:
          - SetPath= /api/microsite/order/{segment}
          - JwtFilter= name,true
      # --------------------
      # Web Payment
      # --------------------
      - id: app-payment
        uri: lb://web-payment
        predicates:
          - Path= /api/payment/{segment}
        filters:
          - SetPath= /api/microsite/payment/{segment}
          - JwtFilter= name,true