# Server
server:
  port: 8101

# Finbox Security
finbox: 
  keystore:
    alias: finbox-sec
    id: finbox-sec-key-id
  auth:
    server: http://localhost:8102

# Eureka Discovery Client Consumer
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8103/eureka